version: '3.8'

services:
  docker101:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5173:5173
    environment:
      - PORT=5173
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
